### ISSUE TITLE
Performance Test

### ISSUE THREAD

**Issue by qingyuanxingsi** [PasaLab/marlin#4]
As for matrix multiplication,how big matrices can you support at most using your current configurations(one 32G master plus sixteen 24G workers)???Looking forward to your reply!

**Comment by Myasuka** [comment]
Sorry for late reply.
The cluster environment has changed in our lab since we added the performance page in Github wiki. Currently, we have one 64GB memory master and twelve 45GB memory executors, and at least the dimensions of dense matrix with `40000x40000` and `40000x40000` have been tested, I think larger diemsnion should also be supported.

**Comment by Myasuka** [comment]
Close this issue now, if you have any questions, please contact me.
