### ISSUE TITLE
How does this compare to Spark's BlockMetrix

### ISSUE THREAD

**Issue by pulasthi** [PasaLab/marlin#5]
From what i understand this library has created a completely new BlockMatrix. How does this compare to the BlockMatrix provided by Spark itself[1]. I am trying to understand what more i can gain by using this library for BlockMatrix for BlockMatrix multiplication.

[1] http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.mllib.linalg.distributed.BlockMatrix

**Comment by Myasuka** [comment]
Actually, when we start this project, Spark has not introduced `BlockMatrix` class. For the convenience of description, we call `BlockMatrix` in Marlin as `MBM` and `BlockMatrix`  in Spark as `SBM` here. 

As far as I know, `MBM` has several difference against `SBM`:
1. `MBM` and `SBM` are both a distributed matrix backed by an RDD of sub-matrices. A sub-matrix in `SBM` is a tuple of `((Int, Int), Matrix)`, where the (Int, Int) is the index of the block, and `Matrix` is the sub-matrix defined by Spark itself. On the other hand, sub-matrix in `MBM` is a tuple of `(BlockID, Matrx)`,  where `BlockID` is a wrapper of row-index and column-index of this sub-matrix, which is simliar to the key of `SBM`, and the `Matrix` directly use `DenseMatrix` in [Breeze](https://github.com/scalanlp/breeze/) instead of creating a self-defined Matrix format.
2. `BlockID` in Marlin is not a simple wrapper over `(Int, Int)`, its real data structure is  `(Int, Int, 0)`, and the 3rd index is assigned value in transformation from `DenseVecMatrix` to `MBM`.
3. Currently, there exists no efficient transforming method from `IndexedRowMatrix`, `CoordinateMatrix` to `SBM` in Spark, and the APIs of  `IndexedRowMatrix` are not compatible with `SBM`, both of them contain some APIs which are exclusive.
4. MLlib supports sparse-block-matrix now, even though it has not been used anywhere in Spark itself. Therefore, supporting for sparse-block-matrix is recorded in our roadmap.

In a word, Spark MLLib mainly focus on machine learning while Marlin focus on distributed matrix computing.

**Comment by pulasthi** [comment]
Thank you for the information and clarification. It seems it is worth while to look into marlin for my use case.

Best Regards,
Pulasthi
